name: 'Mypy'
description: 'Run Mypy and annotate code with errors'
inputs:
  github-token:
    description: 'GitHub token to use for authentication against the GitHub API'
    required: true
  max-errors:
    description: "Max number of warnings before reporting the check as failed"
    required: true
    default: 0
  paths:
    description: "Paths to run mypy on"
    default: "."
outputs:
  num-errors: 
    description: 'Number of errors reported'
runs:
  using: 'node12'
  main: 'dist/index.js'
